item {
  name: "meteor"
  id: 1
  display_name: "meteor"
}
item {
  name: "plane"
  id: 2
  display_name: "plane"
}
item {
  name: "satellite"
  id: 3
  display_name: "satellite"
}
item {
  name: "flare"
  id: 4
  display_name: "flare"
}
item {
  name: "tree"
  id: 5
  display_name: "tree"
}
item {
  name: "satellite"
  id: 6
  display_name: "satellite"
}
